title: 'Shop Settings'
tabs:
  main:
    display: Hauptteil
    sections:
      -
        fields:
          -
            field:
              type: text
              display: 'Shop Title'
              localizable: true
            handle: shop_title
          -
            field:
              type: text
              display: 'Product Category Title (singular)'
              width: 50
              localizable: true
            handle: product_category_singular
          -
            field:
              type: text
              display: 'Product Category Title (plural)'
              width: 50
              localizable: true
            handle: product_category_plural
          -
            field:
              type: text
              display: 'Product Group Title (singular)'
              width: 50
              localizable: true
            handle: product_group_singular
          -
            field:
              type: text
              display: 'Product Group Title (plural)'
              width: 50
              localizable: true
            handle: product_group_plural
          -
            field:
              type: text
              display: 'Product Title (singular)'
              width: 50
              localizable: true
            handle: product_singular
          -
            field:
              type: text
              display: 'Product Title (plural)'
              width: 50
              localizable: true
            handle: product_plural
          -
            field:
              type: text
              display: 'SKU Title (singular)'
              width: 50
              localizable: true
            handle: sku_singular
          -
            field:
              type: text
              display: 'SKU Title (plural)'
              width: 50
              localizable: true
            handle: sku_plural
          -
            field:
              type: text
              display: 'SKU number title (singular)'
              width: 50
              localizable: true
            handle: sku_number_singular
          -
            field:
              type: text
              display: 'SKU number title (plural)'
              width: 50
              localizable: true
            handle: sku_number_plural
          -
            field:
              type: text
              display: 'Packgaging title (singular)'
              width: 50
              localizable: true
            handle: packaging_singular
          -
            field:
              type: text
              display: 'Packgaging title (plural)'
              width: 50
              localizable: true
            handle: packaging_plural
  vat:
    display: VAT
    sections:
      -
        fields:
          -
            field:
              type: text
              display: 'Default VAT'
              localizable: false
            handle: default_vat_percentage
